config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'posts#index'

  resources :users
  resources :posts

end

app/models/post.rb
class Post < ActiveRecord::Base


	belongs_to :user

	validates :title, presence: true
  	# validates :user, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	def name
		"#{first_name} #{last_name}"
	end
   has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :first_name
    devise_parameter_sanitizer.for(:sign_up) << :last_name
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	
	
	def index

	end



end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index
		@posts = Post.all
	end

	def new
		@post = Post.new
	end

	def create
	 @post = current_user.posts.create(params.require(:post).permit(:title, :user, :content))
  	  if @post.save
   	    redirect_to root_path
  	  else
    	render "new"
  	  end
	end
     def destroy
       @post = Post.find(params[:id])
       @post.destroy
     
       respond_to do |format|
         format.html { redirect_to(posts_url) }
         format.xml  { head :ok }
       end
     end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  #route for login form
	def new
	end


   #processes data from login form
	def create
		# @user = User.where(email: params[:email]).first 
  #         if @user && @user.password == params[:password]
  #           session[:user_id] = @user.id   
  #            redirect_to home_path 
  #       end  
  #     end
  #   end
	

    user = User.find_by_email(params[:email])   
    if user && user.authenticate(params[:password])     
      session[:user_id] = user.id     
      redirect_to root_path, :notice => "Welcome back, #{user.email}"  
    else     
      flash[:alert] = "Invalid email or password"
      render "new"
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users = User.all
		if @users.present?
			flash[:notice] = "yay,there are users!"
		else
			flash[:alert] = "sad face. no users"
		end
	end

  def show
  	
  	@user = User.find(params['id'])
  end

  def new
  	@user = User.new
  end

  def destroy

  end


   #this is for form submission in rails

  def create
    byebug
    @user = User.create(user_params) 
    if @user.save    
      flash[:notice] = "Your account was created successfully."    
      redirect_to user_path @user  
    else    
      flash[:alert] = "There was a problem saving your account."   
      redirect_to new_user_path  
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1>Welcome!</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BloggingApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

   <% if user_signed_in? %>
 	 <li>
  	 <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
  	 </li>
   <% else %>
  	 <li>
  	 <%= link_to('Login', new_user_session_path)  %>  
 	 </li>
   <% end %>

	<div>
	  <div>
  	  	<% if flash[:notice] %>
      		<p class="notice"><%= notice %></p>
  	  	<% end %>
  	  	<% if flash[:alert] %>
      		<p class="alert"><%= alert %></p>
  	  	<% end %>
	  </div>
	</div>




<%= yield %>
		

</body>
</html>

app/views/posts/index.html.erb
<div id="logo"> BLOG BLOG..</div>
<h1>Posts</h1>

<% @posts.each do |post| %>
  <div class="post">

    <h4> <%= post.title %> </h4>

    <p> <%= post.name %> </p>

    <p> <%= post.user ? post.user.email : "" %> </p>

    <p> <%= post.content  %> </p>

    <p><%= button_to "delete", post, :method=>:delete, :class=>:destroy %></p>
  </div>
<% end %>

<p><%= link_to "Add a Post", new_post_path %></p>

app/views/posts/new.html.erb
<br>
<br>
<%= form_for @post do |f| %>  
 <%=f.label :name %>  
  <%=f.text_field :name %>  

  <%=f.label :title %>
  <%=f.text_field :title %>
<br>
<br>
  <%=f.label :content %>
  <%=f.text_area :content %>

  <%=f.submit :create %> 
  <% end %>

app/views/users/index.html.erb
<% if @users %>
<%= table_of_users(@users) %>

<% end %>

app/views/users/show.html.erb
<%= @user.name %>


<div>
<%= link_to("Delete User", user_path(@user.id), :method => :delete) %> 
</div>